spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopclien?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 175.178.23.246
    port: 6379
    database: 0
    connect-timeout: 100000
    timeout: 100000
    password: 1029384756qwe`

mybatis:
  mapper-locations: classpath:mybatis/*.xml
server:
  port: 9999

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: countSql


jwt:
  key: popopo!213qwe21